version: '3.8'

services:
  db:
    image: mlatino29/tienda-database-mysql-01:latest
    container_name: database-container
    environment:
      MYSQL_ROOT_PASSWORD: passDB123
      MYSQL_DATABASE: ecommerce_api_prod01
    ports:
      - "3333:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: mlatino29/tienda-api-django-01:latest
    container_name: api-container
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: passDB123
      DB_NAME: ecommerce_api_prod01
    depends_on:
      - db
    ports:
      - "8000:8000"

  php:
    image: mlatino29/tienda-cliente-php-01:latest
    container_name: php-container
    depends_on:
      - db
    ports:
      - "8011:80"

  angular:
    image: mlatino29/tienda-admin-angular-01:latest
    container_name: angular-container
    ports:
      - "4255:4200"

volumes:
  db_data:

